## Asa Has tken out most things that would be the same for every env if we make any changes, they should be made in the templates/values.yaml to affect all things.

image:
  # Commented out above because we use what the pipeline provides as well as top level customization in the template values.yaml
  # repository is the container image prefixed by the registry name.
  # repository: docker.artpro.digitalglobe.com/eck/eck-operator
  # pullPolicy is the container image pull policy.
  
  pullPolicy: IfNotPresent
  # tag is the container image tag. If not defined, defaults to chart appVersion.
  # This field controls the version that is deployed. 
  tag: 1.9.0

# imagePullSecrets defines the secrets to use when pulling the operator container image.
# Commented out because we use what the pipeline provdes here through customization of the template
# imagePullSecrets: []


# config values for the operator.
# These are left excet the containerRegistry because we might need to adjust per env
config:
  # logVerbosity defines the logging level. Valid values are as follows:
  # -2: Errors only
  # -1: Errors and warnings
  #  0: Errors, warnings, and information
  #  number greater than 0: Errors, warnings, information, and debug details. 
  logVerbosity: "0"

  # metricsPort defines the port to expose operator metrics. Set to 0 to disable metrics reporting.
  metricsPort: "0"

  # containerRegistry to use for pulling Elasticsearch and other application container images.
  # Commented out because we use what the pipeline provdes here through customization of the template
  # containerRegistry: docker.artpro.digitalglobe.com:443

  # maxConcurrentReconciles is the number of concurrent reconciliation operations to perform per controller.
  maxConcurrentReconciles: "3"

  # caValidity defines the validity period of the CA certificates generated by the operator.
  caValidity: 8760h

  # caRotateBefore defines when to rotate a CA certificate that is due to expire.
  caRotateBefore: 24h

  # certificatesValidity defines the validity period of certificates generated by the operator.
  certificatesValidity: 8760h

  # certificatesRotateBefore defines when to rotate a certificate that is due to expire.
  certificatesRotateBefore: 24h

  # setDefaultSecurityContext determines whether a default security context is set on application containers created by the operator.
  setDefaultSecurityContext: true

  # kubeClientTimeout sets the request timeout for Kubernetes API calls made by the operator.
  kubeClientTimeout: 60s

  # elasticsearchClientTimeout sets the request timeout for Elasticsearch API calls made by the operator.
  elasticsearchClientTimeout: 180s

  # validateStorageClass specifies whether storage classes volume expansion support should be verified.
  # Can be disabled if cluster-wide storage class RBAC access is not available.
  validateStorageClass: true
