apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elastic-operator
  namespace: elastic-system
  labels:
    control-plane: elastic-operator
spec:
  selector:
    matchLabels:
      control-plane: elastic-operator
  serviceName: elastic-operator
  template:
    spec:
      containers:
      - image: docker.artpro.digitalglobe.com/eck/eck-operator:1.2.0
        name: manager
        env:
          - name: OPERATOR_IMAGE
            value: docker.artpro.digitalglobe.com/eck/eck-operator:1.2.0
 
